// <auto-generated />
using System;
using AttendanceSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceSystem.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260708065448_AddEmployeeRegistrationExtraFields")]
    partial class AddEmployeeRegistrationExtraFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantUserId");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStatus");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalType");

                    b.Property<string>("AttachmentUrls")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("AttachmentUrls");

                    b.Property<string>("BusinessTripDestination")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("BusinessTripDestination");

                    b.Property<decimal?>("BusinessTripDurationDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("BusinessTripDurationDays");

                    b.Property<DateTime?>("BusinessTripEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BusinessTripEndTime");

                    b.Property<DateTime?>("BusinessTripStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BusinessTripStartTime");

                    b.Property<decimal?>("LeaveDurationHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("LeaveDurationHours");

                    b.Property<DateTime?>("LeaveEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LeaveEndTime");

                    b.Property<DateTime?>("LeaveStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LeaveStartTime");

                    b.Property<int?>("LeaveType")
                        .HasColumnType("int")
                        .HasColumnName("LeaveType");

                    b.Property<decimal?>("OvertimeDurationHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("OvertimeDurationHours");

                    b.Property<DateTime?>("OvertimeEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OvertimeEndTime");

                    b.Property<DateTime?>("OvertimeStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OvertimeStartTime");

                    b.Property<DateOnly?>("PunchDate")
                        .HasColumnType("date")
                        .HasColumnName("PunchDate");

                    b.Property<TimeOnly?>("PunchTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("PunchTime");

                    b.Property<int?>("PunchType")
                        .HasColumnType("int")
                        .HasColumnName("PunchType");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Reason");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RequestNo");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SubmittedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalRequest");

                    b.HasIndex("RequestNo")
                        .IsUnique();

                    b.HasIndex("ApplicantUserId", "ApprovalStatus");

                    b.ToTable("ApprovalRequest");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalRequestId");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStatus");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApproverUserId");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("HandledAt");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("StepOrder");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalStep");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("IX_ApprovalStep_ApprovalRequestId");

                    b.HasIndex("ApproverUserId")
                        .HasDatabaseName("IX_ApprovalStep_ApproverUserId");

                    b.ToTable("ApprovalStep");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClerkUserId")
                        .HasColumnType("int")
                        .HasColumnName("ClerkUserId");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DinnerBreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DinnerBreakMinutes");

                    b.Property<bool>("EnableLocationPunch")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EnableLocationPunch");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GroupName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("LunchBreakMinutes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("PK_AttendanceGroup");

                    b.ToTable("AttendanceGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "总公司",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DinnerBreakMinutes = 30,
                            EnableLocationPunch = false,
                            GroupName = "总公司考勤组",
                            IsActive = true,
                            LunchBreakMinutes = 60,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroupApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_AttendanceGroupApprover");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AttendanceGroupApprover_UserId");

                    b.HasIndex("AttendanceGroupId", "UserId")
                        .IsUnique();

                    b.ToTable("AttendanceGroupApprover");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroupLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("Latitude");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("LocationName");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("Longitude");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("int")
                        .HasColumnName("RadiusMeters");

                    b.HasKey("Id")
                        .HasName("PK_AttendanceGroupLocation");

                    b.HasIndex("AttendanceGroupId")
                        .HasDatabaseName("IX_AttendanceGroupLocation_AttendanceGroupId");

                    b.ToTable("AttendanceGroupLocation");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendancePunch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DeviceInfo");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsValid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("Latitude");

                    b.Property<bool?>("LocationValid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("LocationValid");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("Longitude");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PunchTime");

                    b.Property<int>("PunchType")
                        .HasColumnType("int")
                        .HasColumnName("PunchType");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_AttendancePunch");

                    b.HasIndex("UserId", "PunchTime");

                    b.ToTable("AttendancePunch");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualWorkHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ActualWorkHours");

                    b.Property<string>("ApprovalNote")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ApprovalNote");

                    b.Property<int>("AttendanceStatus")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceStatus");

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ClockInTime");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ClockOutTime");

                    b.Property<int>("EarlyLeaveMinutes")
                        .HasColumnType("int")
                        .HasColumnName("EarlyLeaveMinutes");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsHoliday");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("LateMinutes");

                    b.Property<bool>("LocationAbnormal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("LocationAbnormal");

                    b.Property<string>("LocationAbnormalNote")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("LocationAbnormalNote");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("OvertimeHours");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Remark");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ScheduledEndTime");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ScheduledStartTime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id")
                        .HasName("PK_AttendanceRecord");

                    b.HasIndex("UserId", "WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecord");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DeptCode");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DeptName");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasColumnName("SortIndex");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("PK_Department");

                    b.HasIndex("AttendanceGroupId")
                        .HasDatabaseName("IX_Department_AttendanceGroupId");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Department_ParentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "总公司",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = "HQ",
                            DeptName = "总公司",
                            IsActive = true,
                            SortIndex = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.EmployeeRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedUserId")
                        .HasColumnType("int")
                        .HasColumnName("ConfirmedUserId");

                    b.Property<string>("ContractCompany")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ContractCompany");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmergencyContactName");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EmergencyContactPhone");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("HomeAddress");

                    b.Property<string>("IdCardPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IdCardPhotoUrl");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("IdNumber");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Position");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RealName");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("RejectReason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReviewedAt");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SubmittedAt");

                    b.HasKey("Id")
                        .HasName("PK_EmployeeRegistration");

                    b.HasIndex("ConfirmedUserId")
                        .HasDatabaseName("IX_EmployeeRegistration_ConfirmedUserId");

                    b.HasIndex("IdNumber");

                    b.HasIndex("Phone");

                    b.ToTable("EmployeeRegistration");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("HolidayDate");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HolidayName");

                    b.Property<int>("HolidayType")
                        .HasColumnType("int")
                        .HasColumnName("HolidayType");

                    b.HasKey("Id")
                        .HasName("PK_Holiday");

                    b.HasIndex("AttendanceGroupId")
                        .HasDatabaseName("IX_Holiday_AttendanceGroupId");

                    b.HasIndex("HolidayDate", "AttendanceGroupId");

                    b.ToTable("Holiday");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.MonthlyAttendanceSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsentDays")
                        .HasColumnType("int")
                        .HasColumnName("AbsentDays");

                    b.Property<int>("ActualWorkdays")
                        .HasColumnType("int")
                        .HasColumnName("ActualWorkdays");

                    b.Property<int>("ApprovedCount")
                        .HasColumnType("int")
                        .HasColumnName("ApprovedCount");

                    b.Property<int>("EarlyLeaveCount")
                        .HasColumnType("int")
                        .HasColumnName("EarlyLeaveCount");

                    b.Property<int>("ExpectedWorkdays")
                        .HasColumnType("int")
                        .HasColumnName("ExpectedWorkdays");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("GeneratedAt");

                    b.Property<int>("LateCount")
                        .HasColumnType("int")
                        .HasColumnName("LateCount");

                    b.Property<decimal>("LeaveDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("LeaveDays");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("Month");

                    b.Property<int>("NotPunchedCount")
                        .HasColumnType("int")
                        .HasColumnName("NotPunchedCount");

                    b.Property<decimal>("TotalOvertimeHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TotalOvertimeHours");

                    b.Property<decimal>("TotalWorkHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TotalWorkHours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id")
                        .HasName("PK_MonthlyAttendanceSummary");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyAttendanceSummary");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsRead");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NotificationType");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReadAt");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("RelatedId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_Notification");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notification_UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsAutoAssigned");

                    b.Property<int>("ShiftScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftScheduleId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id")
                        .HasName("PK_ShiftAssignment");

                    b.HasIndex("ShiftScheduleId")
                        .HasDatabaseName("IX_ShiftAssignment_ShiftScheduleId");

                    b.HasIndex("UserId", "WorkDate")
                        .IsUnique();

                    b.ToTable("ShiftAssignment");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ShiftSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("EarliestClockInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("EarliestClockInMinutes");

                    b.Property<int>("EarlyLeaveToleranceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("EarlyLeaveToleranceMinutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsCrossDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCrossDay");

                    b.Property<int>("LateToleranceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("LateToleranceMinutes");

                    b.Property<int>("OvertimeThresholdMinutes")
                        .HasColumnType("int")
                        .HasColumnName("OvertimeThresholdMinutes");

                    b.Property<string>("RestDaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RestDaysOfWeek");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ShiftName");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int")
                        .HasColumnName("ShiftType");

                    b.Property<decimal>("StandardWorkHours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("StandardWorkHours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<TimeOnly>("WorkEndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkEndTime");

                    b.Property<TimeOnly>("WorkStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("WorkStartTime");

                    b.HasKey("Id")
                        .HasName("PK_ShiftSchedule");

                    b.HasIndex("AttendanceGroupId")
                        .HasDatabaseName("IX_ShiftSchedule_AttendanceGroupId");

                    b.ToTable("ShiftSchedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceGroupId = 1,
                            Color = "#1890ff",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarliestClockInMinutes = 60,
                            EarlyLeaveToleranceMinutes = 5,
                            IsActive = true,
                            IsCrossDay = false,
                            LateToleranceMinutes = 5,
                            OvertimeThresholdMinutes = 30,
                            RestDaysOfWeek = "0,6",
                            ShiftName = "正常班",
                            ShiftType = 1,
                            StandardWorkHours = 8m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkEndTime = new TimeOnly(18, 0, 0),
                            WorkStartTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceGroupId");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AvatarUrl");

                    b.Property<string>("ContractCompany")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ContractCompany");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("DingTalkUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("DingTalkUserId");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmergencyContactName");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EmergencyContactPhone");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmployeeNo");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("HireDate");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("HomeAddress");

                    b.Property<string>("IdCardPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IdCardPhotoUrl");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("IdNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBlacklisted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Position");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RealName");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<int?>("SupervisorUserId")
                        .HasColumnType("int")
                        .HasColumnName("SupervisorUserId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("AttendanceGroupId")
                        .HasDatabaseName("IX_User_AttendanceGroupId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_User_DepartmentId");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.HasIndex("IdNumber");

                    b.HasIndex("Phone");

                    b.HasIndex("SupervisorUserId")
                        .HasDatabaseName("IX_User_SupervisorUserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "Applicant")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalRequest_User_ApplicantUserId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ApprovalStep", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalStep_ApprovalRequest_ApprovalRequestId");

                    b.HasOne("AttendanceSystem.Models.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalStep_User_ApproverUserId");

                    b.Navigation("ApprovalRequest");

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroupApprover", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany("Approvers")
                        .HasForeignKey("AttendanceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceGroupApprover_AttendanceGroup_AttendanceGroupId");

                    b.HasOne("AttendanceSystem.Models.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceGroupApprover_User_UserId");

                    b.Navigation("Approver");

                    b.Navigation("AttendanceGroup");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroupLocation", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany("Locations")
                        .HasForeignKey("AttendanceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceGroupLocation_AttendanceGroup_AttendanceGroupId");

                    b.Navigation("AttendanceGroup");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendancePunch", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttendancePunch_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceRecord_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Department", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany("Departments")
                        .HasForeignKey("AttendanceGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Department_AttendanceGroup_AttendanceGroupId");

                    b.HasOne("AttendanceSystem.Models.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Department_Department_ParentId");

                    b.Navigation("AttendanceGroup");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.EmployeeRegistration", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "ConfirmedUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_EmployeeRegistration_User_ConfirmedUserId");

                    b.Navigation("ConfirmedUser");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Holiday", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany()
                        .HasForeignKey("AttendanceGroupId")
                        .HasConstraintName("FK_Holiday_AttendanceGroup_AttendanceGroupId");

                    b.Navigation("AttendanceGroup");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.MonthlyAttendanceSummary", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyAttendanceSummary_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Notification", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.ShiftSchedule", "ShiftSchedule")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignment_ShiftSchedule_ShiftScheduleId");

                    b.HasOne("AttendanceSystem.Models.Entities.User", "User")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignment_User_UserId");

                    b.Navigation("ShiftSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ShiftSchedule", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany("ShiftSchedules")
                        .HasForeignKey("AttendanceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShiftSchedule_AttendanceGroup_AttendanceGroupId");

                    b.Navigation("AttendanceGroup");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.User", b =>
                {
                    b.HasOne("AttendanceSystem.Models.Entities.AttendanceGroup", "AttendanceGroup")
                        .WithMany("Users")
                        .HasForeignKey("AttendanceGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_User_AttendanceGroup_AttendanceGroupId");

                    b.HasOne("AttendanceSystem.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_User_Department_DepartmentId");

                    b.HasOne("AttendanceSystem.Models.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_User_User_SupervisorUserId");

                    b.Navigation("AttendanceGroup");

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("ApprovalSteps");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.AttendanceGroup", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Departments");

                    b.Navigation("Locations");

                    b.Navigation("ShiftSchedules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.ShiftSchedule", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("AttendanceSystem.Models.Entities.User", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Notifications");

                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
