# -*- coding: utf-8 -*-
"""Generate attendance system test case Excel."""

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

OUTPUT = r"C:\Users\wuwenzhe\Desktop\AttendanceSystem\测试用例_考勤系统.xlsx"

# (ID, 模块, 用例名称, 优先级, 前置条件, 测试步骤, 预期结果)
CASES = [
    # ── 模块 A：登录/登出/密码 ──
    ("A-01", "登录/登出", "各角色正常登录", "P0",
     "系统已启动；对应角色测试账号已创建且 IsActive=true",
     "1. 访问根路径 /\n2. 输入正确工号和密码\n3. 可选勾选「记住我」\n4. 点击登录\n5. 分别用 Admin/Clerk/Supervisor/TeamLeader/Employee 重复",
     "跳转登录页；登录成功写入 Cookie（8小时有效）；Admin/Clerk→/Admin/Dashboard，Supervisor/TeamLeader→/Approval/PendingApproval，Employee→/Attendance/PunchCard"),
    ("A-02-1", "登录/登出", "工号或密码为空", "P0",
     "未登录",
     "1. 访问 /Login\n2. 工号留空，仅填密码\n3. 提交表单",
     "提示「工号和密码不能为空」，停留在登录页"),
    ("A-02-2", "登录/登出", "密码错误", "P0",
     "存在有效员工账号 emp01",
     "1. 输入正确工号 + 错误密码\n2. 提交",
     "提示「工号或密码错误，请重新输入」，不写入 Cookie"),
    ("A-02-3", "登录/登出", "工号不存在", "P1",
     "未登录",
     "1. 输入不存在的工号\n2. 提交",
     "提示「工号或密码错误，请重新输入」"),
    ("A-02-4", "登录/登出", "已停用账号登录", "P0",
     "存在 IsActive=false 的账号",
     "1. 使用该账号工号密码登录",
     "登录失败，提示工号或密码错误"),
    ("A-02-5", "登录/登出", "已登录访问登录页", "P2",
     "用户已登录",
     "1. 已登录状态下访问 /Login",
     "自动跳转到该角色对应首页，不重复登录"),
    ("A-03", "登录/登出", "正常登出", "P0",
     "用户已登录",
     "1. 访问 /Logout 或 POST /api/account/logout\n2. 访问需登录页面",
     "会话清除；再次访问受保护页面重定向到 /Login"),
    ("A-04-1", "登录/登出", "正常修改密码", "P0",
     "用户已登录，已知当前密码",
     "1. 访问 /Account/ChangePassword\n2. 输入正确原密码和新密码\n3. 提交\n4. 登出后用新密码登录",
     "提示密码修改成功；新密码可登录，旧密码不可登录"),
    ("A-04-2", "登录/登出", "原密码错误改密", "P1",
     "用户已登录",
     "1. 访问改密页\n2. 输入错误原密码\n3. 提交",
     "提示「原密码错误」，密码未变更"),
    ("A-04-3", "登录/登出", "未登录修改密码", "P1",
     "未登录，无 Cookie",
     "1. POST /api/account/change-password",
     "返回 401 Unauthorized"),
    ("A-05-1", "权限控制", "Employee 访问管理页", "P0",
     "Employee 角色已登录",
     "1. 直接访问 /Admin/Dashboard",
     "跳转 /Login?denied=1 或 403，无法访问"),
    ("A-05-2", "权限控制", "Employee 调用部门考勤 API", "P0",
     "Employee 已登录",
     "1. GET /api/attendance/department?startDate=2026-01-01&endDate=2026-01-31",
     "403 Forbidden"),
    ("A-05-3", "权限控制", "Employee 访问待审批", "P0",
     "Employee 已登录",
     "1. 访问 /Approval/PendingApproval\n2. GET /api/approval/pending-for-me",
     "403 Forbidden，无法审批"),

    # ── 模块 B：打卡与考勤 ──
    ("B-01-1", "打卡考勤", "正常上下班打卡", "P0",
     "工作日；员工已分配 09:00-18:00 班次；非节假日",
     "1. emp01 登录\n2. 09:00 前在 /Attendance/PunchCard 打上班卡\n3. 18:00 后打下班卡\n4. 查看今日状态",
     "上班/下班时间记录正确；AttendanceStatus=正常；ActualWorkHours>0"),
    ("B-01-2", "打卡考勤", "仅上班未下班", "P1",
     "同上",
     "1. 打上班卡\n2. 不打下班卡\n3. GET /api/attendance/today",
     "ClockInTime 有值，ClockOutTime 为空"),
    ("B-01-3", "打卡考勤", "重复上班打卡", "P2",
     "当日已打上班卡",
     "1. 再次点击上班打卡",
     "打卡成功，ClockInTime 更新为最新时间"),
    ("B-01-4", "打卡考勤", "先下班后上班", "P2",
     "当日无考勤记录",
     "1. 先打下班卡\n2. 再打上班卡",
     "系统允许写入；ClockOut/ClockIn 均有值，状态按逻辑计算"),
    ("B-02-1", "打卡考勤", "迟到判定", "P0",
     "排班 09:00 开始，LateToleranceMinutes=5",
     "1. 09:06 打上班卡",
     "AttendanceStatus=迟到；LateMinutes=6；提示含「迟到 6 分钟」"),
    ("B-02-2", "打卡考勤", "容忍内不算迟到", "P1",
     "排班 09:00，容忍 5 分钟",
     "1. 09:04 打上班卡",
     "AttendanceStatus=正常；LateMinutes=0"),
    ("B-02-3", "打卡考勤", "早退判定", "P0",
     "排班 18:00 结束，EarlyLeaveToleranceMinutes=5",
     "1. 正常上班打卡\n2. 17:50 打下班卡",
     "AttendanceStatus=早退；EarlyLeaveMinutes 有值"),
    ("B-02-4", "打卡考勤", "加班工时计算", "P0",
     "排班 18:00 结束，OvertimeThresholdMinutes=30",
     "1. 正常上班\n2. 18:35 下班打卡",
     "OvertimeHours>0"),
    ("B-02-5", "打卡考勤", "未达加班阈值", "P1",
     "OvertimeThresholdMinutes=30",
     "1. 18:20 下班打卡",
     "OvertimeHours=0"),
    ("B-02-6", "打卡考勤", "跨天班次", "P1",
     "分配 22:00-06:00 跨天班 IsCrossDay=true",
     "1. 22:00 前上班打卡\n2. 次日 06:30 下班打卡",
     "ScheduledEndTime 跨天；早退/加班计算正确"),
    ("B-03-1", "打卡考勤", "标准8小时工时", "P1",
     "09:00-18:00 班次，默认午休60分钟",
     "1. 09:00 上班 18:00 下班",
     "ActualWorkHours≈8.00（扣除午休）"),
    ("B-03-2", "打卡考勤", "超9小时扣晚餐", "P2",
     "默认 DinnerBreakMinutes=30",
     "1. 09:00 上班 20:00 下班",
     "扣除午休+晚餐后 ActualWorkHours 正确"),
    ("B-03-3", "打卡考勤", "无排班打卡", "P1",
     "员工当日无 ShiftAssignment",
     "1. 打上班/下班卡",
     "打卡成功；迟到/早退/加班均为0或Normal"),
    ("B-03-4", "打卡考勤", "自定义午休时长", "P2",
     "考勤组 LunchBreakMinutes=90",
     "1. 09:00-18:00 完整打卡",
     "工时按90分钟午休扣减"),
    ("B-04-1", "打卡考勤", "法定节假日不可打卡", "P0",
     "当日 Holiday 类型=LegalHoliday",
     "1. 员工尝试上班打卡",
     "失败，提示「今日为节假日，无需打卡」"),
    ("B-04-2", "打卡考勤", "公司休息日不可打卡", "P0",
     "当日 Holiday 类型=CompanyRestDay",
     "1. 尝试打卡",
     "失败，提示节假日无需打卡"),
    ("B-04-3", "打卡考勤", "调班补班日可打卡", "P1",
     "周六设为 CompensatoryWorkDay",
     "1. 周六打上班/下班卡",
     "打卡成功"),
    ("B-04-4", "打卡考勤", "考勤组专属假期", "P2",
     "组A有假期，组B无",
     "1. 两组员工同日打卡",
     "组A不可打卡，组B可打卡"),
    ("B-05-1", "定位打卡", "范围内定位打卡", "P1",
     "考勤组 EnableLocationPunch=true，坐标在 PunchRadiusMeters 内",
     "1. 允许浏览器定位\n2. 在范围内打上班卡",
     "打卡成功"),
    ("B-05-2", "定位打卡", "超出范围打卡", "P1",
     "启用定位打卡，坐标超出半径",
     "1. 传入超出范围的经纬度\n2. 打卡",
     "失败，提示距打卡点距离及限制米数"),
    ("B-05-3", "定位打卡", "未授权定位", "P1",
     "考勤组启用定位，不传坐标",
     "1. POST /api/attendance/punch 不含 latitude/longitude",
     "失败，提示需允许位置权限"),
    ("B-05-4", "定位打卡", "未启用定位", "P1",
     "EnableLocationPunch=false",
     "1. 不传坐标打卡",
     "打卡成功"),
    ("B-06-1", "打卡考勤", "今日无考勤记录", "P1",
     "当日未打卡",
     "1. GET /api/attendance/today",
     "Success=true，Data=null"),
    ("B-06-2", "打卡考勤", "今日有记录查询", "P1",
     "当日已打卡",
     "1. GET /api/attendance/today",
     "返回完整 AttendanceRecordDto"),
    ("B-06-3", "打卡考勤", "个人月度记录页", "P1",
     "当月有多条考勤记录",
     "1. 访问 /Attendance/MyRecord\n2. 选择年月",
     "列表与汇总摘要正确展示"),
    ("B-06-4", "打卡考勤", "日期范围过滤", "P2",
     "有多日记录",
     "1. GET /api/attendance/personal?startDate=&endDate=",
     "仅返回范围内记录"),
    ("B-06-5", "打卡考勤", "未登录访问考勤 API", "P0",
     "无 Cookie",
     "1. GET /api/attendance/today",
     "401 或跳转登录"),

    # ── 模块 C：审批 ──
    ("C-01-1", "审批", "提交补上班卡申请", "P0",
     "emp01 已登录；有直属上级或审批流",
     "1. /Approval/ApplySubmit 选补卡\n2. 填日期、ClockIn、时间、原因\n3. 提交",
     "单号 BK+日期+序号；ApprovalStatus=Pending；第一审批人收到通知"),
    ("C-01-2", "审批", "提交补下班卡申请", "P1",
     "同上",
     "1. 选 PunchType=ClockOut 提交",
     "申请创建成功，单号正确"),
    ("C-01-3", "审批", "申请带附件", "P1",
     "准备 ≤5 个 ≤10MB 文件",
     "1. 提交申请时上传附件",
     "AttachmentUrls 保存，页面可访问 /uploads/approvals/..."),
    ("C-01-4", "审批", "超大附件跳过", "P2",
     "准备 >10MB 文件",
     "1. 上传超大文件提交",
     "该文件被跳过，其余正常保存"),
    ("C-01-5", "审批", "超过5个附件", "P2",
     "准备6个合法文件",
     "1. 一次上传6个附件",
     "仅保存前5个"),
    ("C-02-1", "审批", "提交请假申请", "P0",
     "emp01 已登录",
     "1. 选请假类型（事假/病假/年假等）\n2. 填起止时间、原因\n3. 提交",
     "单号 QJ 开头；LeaveDurationHours 自动计算"),
    ("C-02-2", "审批", "跨天请假", "P1",
     "同上",
     "1. 请假 1/10-1/12 提交",
     "LeaveDurationHours 为跨天小时数"),
    ("C-03-1", "审批", "提交加班申请", "P1",
     "emp01 已登录",
     "1. 填 OvertimeStart/End 和原因\n2. 提交",
     "单号 JB 开头；OvertimeDurationHours 正确"),
    ("C-04-1", "审批", "组审批人名单路由", "P0",
     "考勤组配置了 AttendanceGroupApprover 名单（多人）",
     "1. 提交申请时从下拉框选一个名单里的审批人\n2. 查 ApprovalStep",
     "仅创建 StepOrder=1、ApproverUserId=所选人 的 Pending 节点"),
    ("C-04-1b", "审批", "审批人不在名单内被拒绝", "P0",
     "考勤组配置了审批人名单",
     "1. 绕开下拉框，直接提交一个不在名单里的 ApproverUserId",
     "提交失败，报错「请选择有效的审批人」"),
    ("C-04-2", "审批", "组未配置审批人回退直属上级", "P0",
     "考勤组未配置审批人名单，员工有 SupervisorUserId",
     "1. 提交申请",
     "仅创建 StepOrder=1 的上级审批节点"),
    ("C-04-3", "审批", "组未配置审批人且无上级", "P2",
     "考勤组未配置审批人名单，员工无 SupervisorUserId",
     "1. 提交申请",
     "兜底指派在职管理员/文员为审批人"),
    ("C-05-1", "审批", "单级审批通过", "P0",
     "待审批补卡申请，sup01 为审批人",
     "1. sup01 登录 PendingApproval\n2. 点击通过",
     "ApprovalStatus=Approved；通知申请人；考勤回写"),
    ("C-05-2", "审批", "单级审批驳回", "P0",
     "有待审批申请",
     "1. 审批人填驳回原因\n2. 驳回",
     "ApprovalStatus=Rejected；通知申请人"),
    ("C-05-3", "审批", "API驳回无原因", "P1",
     "审批人有待办",
     "1. POST /api/approval/handle IsApproved=false Comment 为空",
     "400「驳回时必须填写驳回原因」"),
    ("C-05-4", "审批", "多级第一级通过", "P0",
     "配置了2级以上审批流",
     "1. 第一审批人通过",
     "ApprovalStatus=InProgress；下一审批人收到通知"),
    ("C-05-5", "审批", "多级最后一级通过", "P0",
     "仅剩最后一级 Pending",
     "1. 最后审批人通过",
     "Approved；UpdateAttendanceAfterApproval 执行"),
    ("C-05-6", "审批", "非审批人越权处理", "P1",
     "申请待 userA 审批",
     "1. userB 调用 handle API",
     "Success=false「未找到待处理的审批记录」"),
    ("C-06-1", "审批", "补卡通过回写已有记录", "P0",
     "当日已有 AttendanceRecord；补卡申请已通过",
     "1. 补卡 Approved 后查 AttendanceRecord",
     "ClockIn/ClockOut 补填；ApprovalNote 含单号"),
    ("C-06-2", "审批", "补卡通过无当日记录", "P2",
     "当日无 AttendanceRecord",
     "1. 补卡审批通过",
     "当前实现不新建记录（记录为边界行为）"),
    ("C-06-3", "审批", "请假通过回写", "P0",
     "请假 1/15-1/16 已通过",
     "1. 查两日 AttendanceRecord",
     "AttendanceStatus=OnLeave；ApprovalNote 有备注"),
    ("C-07-1", "审批", "Pending 状态撤销", "P0",
     "申请人有待审批申请",
     "1. ApplySubmit 点撤销或 POST cancel/{id}",
     "ApprovalStatus=Cancelled"),
    ("C-07-2", "审批", "非 Pending 不可撤销", "P1",
     "申请已 Approved/Rejected/InProgress",
     "1. 尝试撤销",
     "失败「仅待审批状态可撤销」"),
    ("C-07-3", "审批", "他人不可撤销", "P1",
     "A 的申请 Pending",
     "1. B 调用 cancel/{id}",
     "撤销失败"),
    ("C-08-1", "审批", "我的申请列表", "P1",
     "用户有多条申请",
     "1. GET /api/approval/mine",
     "返回当前用户全部申请"),
    ("C-08-2", "审批", "按状态筛选申请", "P2",
     "有多种状态申请",
     "1. GET /api/approval/mine?status=Pending",
     "仅 Pending 记录"),
    ("C-08-3", "审批", "待我审批列表", "P1",
     "Supervisor 有待办",
     "1. GET /api/approval/pending-for-me",
     "仅当前用户 Pending 节点对应申请"),
    ("C-08-4", "审批", "管理员审批查询", "P1",
     "Admin 已登录",
     "1. GET /api/approval/query 带分页和筛选",
     "分页正确；可按类型/状态/日期过滤"),
    ("C-08-5", "审批", "申请详情", "P1",
     "存在申请 ID",
     "1. GET /api/approval/{id}",
     "含 Steps 审批链明细"),

    # ── 模块 D：通知 ──
    ("D-01", "通知", "新申请通知审批人", "P1",
     "有审批节点",
     "1. 员工提交申请\n2. GET /api/notifications 审批人账号",
     "审批人收到「您有新的待审批申请」未读通知"),
    ("D-02", "通知", "多级流转通知", "P1",
     "多级审批，第一级已通过",
     "1. 第一级通过\n2. 查下一审批人通知",
     "下一审批人收到流转通知"),
    ("D-03", "通知", "审批结果通知申请人", "P1",
     "审批已完成",
     "1. 通过或驳回\n2. 查申请人通知",
     "收到「审批已通过/已驳回」通知"),
    ("D-04", "通知", "旷工提醒通知", "P1",
     "员工全天未打卡；非节假日",
     "1. 等待或模拟 23:58 后台任务\n2. 查员工通知",
     "收到「今日旷工提醒」；AttendanceStatus=Absent"),
    ("D-05", "通知", "下班未打卡提醒", "P1",
     "有上班无下班",
     "1. 23:58 后台任务执行",
     "NotPunched + 「下班未打卡提醒」通知"),
    ("D-06", "通知", "拉取未读通知", "P1",
     "用户有未读通知",
     "1. GET /api/notifications",
     "返回最近15条 items + count 总数"),
    ("D-07", "通知", "单条标记已读", "P2",
     "有未读通知",
     "1. POST /api/notifications/{id}/read",
     "该条 IsRead=true"),
    ("D-08", "通知", "全部标记已读", "P2",
     "有多条未读",
     "1. POST /api/notifications/read-all",
     "全部未读清零"),
    ("D-09", "通知", "读他人通知", "P1",
     "通知属于用户A",
     "1. 用户B POST read/{A的通知id}",
     "404 Not Found"),

    # ── 模块 E：管理后台 ──
    ("E-01-1", "管理后台", "今日看板统计", "P0",
     "Admin 已登录；有多名员工",
     "1. 访问 /Admin/Dashboard",
     "显示 TotalEmployees/Present/Absent/Late/OnLeave/NotPunched"),
    ("E-01-2", "管理后台", "看板按考勤组筛选", "P2",
     "多个考勤组",
     "1. GET /api/attendance/today-stats?groupId=X",
     "仅统计该组员工"),
    ("E-02-1", "管理后台", "新增员工", "P0",
     "Admin 已登录",
     "1. POST /api/admin/users 或 UserManage 页面\n2. 填工号姓名部门角色初始密码",
     "创建成功；新账号可登录"),
    ("E-02-2", "管理后台", "工号重复", "P1",
     "工号 emp01 已存在",
     "1. 新增同工号员工",
     "失败「工号已存在」"),
    ("E-02-3", "管理后台", "编辑员工", "P1",
     "存在员工",
     "1. PUT /api/admin/users/{id} 修改部门/角色/上级",
     "更新成功"),
    ("E-02-4", "管理后台", "编辑工号冲突", "P2",
     "两名员工 A、B",
     "1. 将 A 工号改为 B 的工号",
     "失败「工号已被其他员工占用」"),
    ("E-02-5", "管理后台", "停用员工", "P0",
     "存在在职员工",
     "1. DELETE /api/admin/users/{id}",
     "IsActive=false；不可登录"),
    ("E-02-6", "管理后台", "重置密码", "P1",
     "Admin 已登录",
     "1. POST /api/admin/users/{id}/reset-password",
     "返回8位随机密码；该密码可登录"),
    ("E-02-7", "管理后台", "员工列表筛选分页", "P2",
     "多名员工",
     "1. GET /api/admin/users?deptId&groupId&role&keyword&pageIndex",
     "筛选和分页正确"),
    ("E-03-1", "管理后台", "部门增删改查", "P1",
     "Admin 已登录",
     "1. POST/PUT /api/admin/departments\n2. GET 列表",
     "部门 CRUD 成功；支持 ParentId"),
    ("E-04-1", "管理后台", "新建考勤组", "P1",
     "Admin 已登录",
     "1. POST /api/admin/attendance-groups\n2. 配置定位/半径/休息",
     "创建成功；配置保存"),
    ("E-05-1", "管理后台", "新建班次", "P1",
     "有关联考勤组",
     "1. POST /api/admin/shifts 固定/弹性/自由班",
     "ShiftType 和时间配置正确保存"),
    ("E-05-2", "管理后台", "编辑班次参数", "P1",
     "已有班次",
     "1. PUT /api/admin/shifts/{id} 改容忍/加班阈值",
     "后续打卡计算使用新参数"),
    ("E-06-1", "管理后台", "新增法定节假日", "P0",
     "Admin 已登录",
     "1. POST /api/admin/holidays LegalHoliday",
     "该日员工不可打卡"),
    ("E-06-2", "管理后台", "新增调班补班日", "P1",
     "选择周末日期",
     "1. POST CompensatoryWorkDay",
     "周末需出勤；后台不跳过旷工标记"),
    ("E-06-3", "管理后台", "删除假期", "P2",
     "存在假期记录",
     "1. DELETE /api/admin/holidays/{id}",
     "删除成功；该日恢复可打卡"),
    ("E-07-1", "管理后台", "考勤组配置审批人名单", "P1",
     "Admin 已登录",
     "1. GroupManage 编辑考勤组，勾选一个或多个审批人保存\n2. 该组员工提交补卡申请",
     "员工提交页出现审批人下拉；按所选人创建审批节点"),

    # ── 模块 F：报表 ──
    ("F-01", "报表", "手动生成月度汇总", "P0",
     "当月有考勤记录",
     "1. POST /api/report/generate-monthly-summary?year=&month=",
     "所有在职员工生成/更新 MonthlyAttendanceSummary"),
    ("F-02", "报表", "汇总字段准确性", "P1",
     "员工有迟到/早退/旷工/请假记录",
     "1. 生成汇总\n2. 对比 AttendanceRecord",
     "LateCount/AbsentDays/LeaveDays/TotalWorkHours 一致"),
    ("F-03", "报表", "应出勤天数计算", "P1",
     "月内含周末/节假日/补班",
     "1. 查 ExpectedWorkdays",
     "符合周末/法定/补班规则"),
    ("F-04", "报表", "导出月度汇总 Excel", "P0",
     "已生成月度汇总；Admin 已登录",
     "1. GET /api/report/export/monthly-summary?year&month",
     "下载 xlsx；文件名含年月；内容可读"),
    ("F-05", "报表", "导出个人每日明细", "P0",
     "已生成该员工月度汇总",
     "1. GET /api/report/export/daily-status/{userId}?year&month",
     "下载含每日明细的 xlsx"),
    ("F-06", "报表", "无汇总导出报表2", "P1",
     "未生成 MonthlyAttendanceSummary",
     "1. 直接 export daily-status",
     "404「未找到对应汇总数据，请先生成月度汇总」"),
    ("F-07", "报表", "个人月度汇总 API", "P1",
     "Employee 已登录",
     "1. GET /api/attendance/monthly-summary?year&month",
     "返回本人汇总"),
    ("F-08", "报表", "部门月度汇总", "P1",
     "Admin 已登录",
     "1. GET /api/attendance/dept-monthly-summary",
     "可按 deptId/groupId 筛选"),
    ("F-09", "报表", "Employee 无权导出", "P1",
     "Employee 已登录",
     "1. 调用 report export API",
     "403 Forbidden"),
    ("F-10", "报表", "MonthlyReport 页面", "P1",
     "Admin 已登录",
     "1. /Report/MonthlyReport 选年月\n2. 查看汇总和弹窗明细\n3. 导出",
     "页面数据与 API/Excel 一致"),

    # ── 模块 G：后台任务 ──
    ("G-01", "后台任务", "全天未打卡标记旷工", "P1",
     "工作日；员工未打卡",
     "1. 等待或模拟 23:58 MarkAbsent\n2. 查 AttendanceRecord",
     "新建 Absent 记录 + 旷工通知"),
    ("G-02", "后台任务", "有上班无下班", "P1",
     "仅 ClockIn 无 ClockOut",
     "1. 23:58 任务执行",
     "NotPunched + 下班提醒"),
    ("G-03", "后台任务", "节假日跳过", "P1",
     "法定节假日",
     "1. 23:58 任务执行",
     "不标记旷工"),
    ("G-04", "后台任务", "普通周末跳过", "P2",
     "周六无补班配置",
     "1. 23:58 任务",
     "不标记"),
    ("G-05", "后台任务", "补班日周末标记", "P2",
     "周六 CompensatoryWorkDay",
     "1. 未打卡\n2. 23:58 任务",
     "正常标记 Absent"),
    ("G-06", "后台任务", "同日去重执行", "P2",
     "23:58-23:59 多次轮询",
     "1. 观察日志/数据库",
     "同一天 MarkAbsent 只执行一次"),
    ("G-07", "后台任务", "月初自动生成汇总", "P1",
     "上月有考勤数据",
     "1. 等待或模拟 1日 00:02",
     "自动生成上月 MonthlyAttendanceSummary"),

    # ── 模块 H：部门考勤 ──
    ("H-01", "部门考勤", "按部门查询", "P1",
     "Admin；部门有员工记录",
     "1. GET /api/attendance/department?departmentId&startDate&endDate",
     "返回部门员工考勤"),
    ("H-02", "部门考勤", "按考勤组查询", "P2",
     "Admin",
     "1. 传 attendanceGroupId",
     "仅该组员工"),
    ("H-03", "部门考勤", "空结果", "P2",
     "无记录日期范围",
     "1. 查询",
     "空列表 Success=true"),

    # ── 模块 I：UI 走查 ──
    ("I-01", "UI", "登录页", "P2",
     "未登录",
     "1. 检查表单/RememberMe/denied=1 提示",
     "UI 正常；错误提示清晰"),
    ("I-02", "UI", "打卡页", "P2",
     "Employee 已登录",
     "1. 检查今日状态/定位/打卡反馈",
     "信息展示正确"),
    ("I-03", "UI", "我的记录页", "P2",
     "有历史记录",
     "1. 切换年月",
     "列表和汇总正确"),
    ("I-04", "UI", "提交申请页", "P2",
     "Employee 已登录",
     "1. 切换补卡/请假/加班\n2. 撤销 Pending",
     "字段联动正确；撤销仅 Pending 可见"),
    ("I-05", "UI", "待审批页", "P2",
     "Supervisor 有待办",
     "1. 列表/详情/通过驳回",
     "操作反馈正确"),
    ("I-06", "UI", "角色菜单权限", "P2",
     "各角色账号",
     "1. 对比导航菜单可见项",
     "菜单与角色权限一致"),

    # ── 模块 J：安全异常 ──
    ("J-01", "安全", "SQL 注入", "P2",
     "未登录或已登录",
     "1. 工号/关键字输入 ' OR 1=1--",
     "无 SQL 异常；EF 参数化安全"),
    ("J-02", "安全", "XSS", "P2",
     "Admin 可编辑字段",
     "1. 姓名/原因输入 <script>alert(1)</script>",
     "页面转义，脚本不执行"),
    ("J-04", "安全", "越权查他人考勤", "P0",
     "Employee A 已登录",
     "1. 尝试修改 personal API userId 为 B",
     "强制 CurrentUserId，仅返回 A 的数据"),
    ("J-05", "安全", "越权审批", "P0",
     "非当前审批人",
     "1. 伪造 ApprovalRequestId 处理",
     "处理失败"),
    ("J-06", "安全", "会话过期", "P2",
     "Cookie 过期或清除",
     "1. 访问受保护页面",
     "重定向登录"),
    ("J-08", "安全", "并发打卡", "P2",
     "同一用户",
     "1. 同时发送两次 POST punch",
     "数据一致，无异常崩溃"),

    # ── 模块 K：端到端 ──
    ("K-01", "端到端", "标准员工一天", "P0",
     "emp01 工作日有排班",
     "1. 登录→09:00上班→18:30下班→查 MyRecord",
     "全流程正常；有加班工时"),
    ("K-02", "端到端", "迟到+补卡闭环", "P0",
     "有审批人",
     "1. 09:30迟到→提交补卡→审批通过→查记录",
     "ClockIn 更新；ApprovalNote 有备注"),
    ("K-03", "端到端", "请假全流程", "P0",
     "多级审批配置",
     "1. 提交请假→逐级通过→查 OnLeave→查月度汇总",
     "请假状态与 LeaveDays 正确"),
    ("K-04", "端到端", "旷工+补卡", "P1",
     "可模拟 23:58",
     "1. 全天不打卡→标记 Absent→次日补卡审批",
     "旷工通知→补卡后记录更新"),
    ("K-05", "端到端", "管理员月度闭环", "P0",
     "Admin；整月数据",
     "1. 配置基础数据→员工打卡→generate汇总→导出报表1/2",
     "Excel 与系统数据一致"),
    ("K-06", "端到端", "Clerk 本组管理", "P1",
     "Clerk 账号",
     "1. Clerk 登录→管理员工→看板→报表",
     "ManagePolicy 功能可用（验证组范围限制）"),
]

HEADERS = ["用例 ID", "模块", "用例名称", "优先级", "前置条件", "测试步骤", "预期结果"]

def main():
    wb = Workbook()
    ws = wb.active
    ws.title = "测试用例"

    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    thin = Side(style="thin", color="B4B4B4")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    wrap = Alignment(wrap_text=True, vertical="top")
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for col, h in enumerate(HEADERS, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = center
        cell.border = border

    priority_fills = {
        "P0": PatternFill(start_color="FFE699", end_color="FFE699", fill_type="solid"),
        "P1": PatternFill(start_color="E2EFDA", end_color="E2EFDA", fill_type="solid"),
        "P2": PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid"),
    }

    for row_idx, case in enumerate(CASES, 2):
        for col_idx, value in enumerate(case, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.alignment = wrap
            cell.border = border
            if col_idx == 4 and value in priority_fills:
                cell.fill = priority_fills[value]
                cell.alignment = center

    widths = [10, 12, 22, 8, 32, 40, 40]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}{len(CASES) + 1}"

    # Summary sheet
    summary = wb.create_sheet("统计")
    summary["A1"] = "考勤系统测试用例统计"
    summary["A1"].font = Font(bold=True, size=14)
    summary["A3"] = "模块"
    summary["B3"] = "用例数"
    summary["A3"].font = summary["B3"].font = Font(bold=True)

    from collections import Counter
    mod_count = Counter(c[1] for c in CASES)
    pri_count = Counter(c[3] for c in CASES)
    row = 4
    for mod, cnt in sorted(mod_count.items()):
        summary.cell(row=row, column=1, value=mod)
        summary.cell(row=row, column=2, value=cnt)
        row += 1
    row += 1
    summary.cell(row=row, column=1, value="合计").font = Font(bold=True)
    summary.cell(row=row, column=2, value=len(CASES)).font = Font(bold=True)
    row += 2
    summary.cell(row=row, column=1, value="优先级").font = Font(bold=True)
    summary.cell(row=row, column=2, value="数量").font = Font(bold=True)
    row += 1
    for pri in ["P0", "P1", "P2"]:
        summary.cell(row=row, column=1, value=pri)
        summary.cell(row=row, column=2, value=pri_count.get(pri, 0))
        row += 1

    summary.column_dimensions["A"].width = 20
    summary.column_dimensions["B"].width = 12

    wb.save(OUTPUT)
    print(f"Generated: {OUTPUT}")
    print(f"Total cases: {len(CASES)}")

if __name__ == "__main__":
    main()
